### ISSUE TITLE
Unable to resolve module 

### ISSUE THREAD

**Issue by haroonob** [yusukeshibata/react-native-audio-polyfill#1]
I am getting following error when I try use this library 
Unable to resolve module event-emitter from node_modules\react-universal-audio\lib\index.native.js

**Comment by yusukeshib** [comment]
@haroonob Thanks for reporting. Fixed on v1.0.2.

**Comment by haroonob** [comment]
Thanks for you quick support. Sorry I didn't mention version I am using. I am using "react-universal-audio": "^1.1.5", version

**Comment by yusukeshib** [comment]
I just changed the package name to `react-native-audio-polyfill`.
I will set deprecated flag to `react-universal-audio`.

Thanks.
