### ISSUE TITLE
Increase frequency of firing `timeupdate` events

### ISSUE THREAD

**Issue by CezarMocan** [yusukeshibata/react-native-audio-polyfill#9]
https://github.com/yusukeshibata/react-native-audio-polyfill/blob/b2b4f55c9abbe755a1478a05bd2b74088c2991be/RNAudio/RNAudioPlayer.m#L155

@yusukeshibata Can we change the timer to fire every 0.2 seconds instead of every 1.0 seconds? I don't have write rights to this repo.

Thanks!!

**Comment by yusukeshib** [comment]
@CezarMocan Thanks! I updated on 1.1.7
